var a = 5
var b = 2
// let suma=a+b
let resta=a-b
let multiplicación=a*b
let division=a/b
let modulo = a % b
console.log(`La suma de ${a} + ${b} = ${a+b}`);
console.log(`La resta de ${a} - ${b} = ${a-b}`);
console.log(`La multiplicación de ${a} * ${b} = ${multiplicación}`);
console.log(`La division de ${a} / ${b} = ${division}`);
console.log(`La division de ${a} % ${b} = ${modulo}`);